# Generated by Django 4.2.4 on 2023-08-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Teams',
        ),
    ]
