# Generated by Django 4.2.4 on 2023-08-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_rename_category_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
